export type PaperSource = {
  id: string;
  author: string;
  title: string;
  date: string;
  url: string;
  kind: 'primary' | 'reporting' | 'peer-reviewed' | 'preprint';
  library?: boolean;
};

export const PAPER_SOURCES = [
  {
    id: 'arora-2008',
    author: 'Arora, Telang and Xu',
    title: 'Optimal Policy for Software Vulnerability Disclosure, Management Science 54(4), 642-656 (abstract only)',
    date: '2008-04',
    url: 'https://doi.org/10.1287/mnsc.1070.0771',
    kind: 'peer-reviewed',
  },
  {
    id: 'herley-2009',
    author: 'Herley and Florêncio',
    title: 'Nobody Sells Gold for the Price of Silver: Dishonesty, Uncertainty and the Underground Economy (Microsoft Research MSR-TR-2009-34; later a Springer chapter)',
    date: '2009-06',
    url: 'https://www.microsoft.com/en-us/research/publication/nobody-sells-gold-for-the-price-of-silver-dishonesty-uncertainty-and-the-underground-economy/',
    kind: 'primary',
  },
  {
    id: 'arora-2010',
    author: 'Arora, Krishnan, Telang and Yang',
    title: "An Empirical Analysis of Software Vendors' Patch Release Behavior: Impact of Vulnerability Disclosure, Information Systems Research 21(1), 115-132 (abstract only)",
    date: '2010-03',
    url: 'https://doi.org/10.1287/isre.1080.0226',
    kind: 'peer-reviewed',
  },
  {
    id: 'bilge-2012',
    author: 'Bilge and Dumitraș',
    title: 'Before We Knew It: An Empirical Study of Zero-Day Attacks in the Real World (ACM CCS 2012, author copy)',
    date: '2012-10',
    url: 'https://users.umiacs.umd.edu/~tdumitra/papers/CCS-2012.pdf',
    kind: 'peer-reviewed',
  },
  {
    id: 'hutchings-holt-2015',
    author: 'Hutchings and Holt',
    title: 'A Crime Script Analysis of the Online Stolen Data Market, British Journal of Criminology 55(3), 596-614',
    date: '2015 (online 2014-12-29)',
    url: 'https://doi.org/10.1093/bjc/azu106',
    kind: 'peer-reviewed',
    library: true,
  },
  {
    id: 'leukfeldt-2017',
    author: 'Leukfeldt, Kleemans and Stol',
    title: 'Cybercriminal Networks, Social Ties and Online Forums: Social Ties Versus Digital Ties within Phishing and Malware Networks, British Journal of Criminology 57(3), 704-722',
    date: '2017 (online 2016-02-03)',
    url: 'https://doi.org/10.1093/bjc/azw009',
    kind: 'peer-reviewed',
    library: true,
  },
  {
    id: 'hutchings-clayton-2016',
    author: 'Hutchings and Clayton',
    title: 'Exploring the Provision of Online Booter Services, Deviant Behavior 37(10), 1163-1178',
    date: '2016-05-09',
    url: 'https://doi.org/10.1080/01639625.2016.1169829',
    kind: 'peer-reviewed',
    library: true,
  },
  {
    id: 'dupont-2017',
    author: 'Dupont',
    title: 'Bots, cops, and corporations: on the limits of enforcement and the promise of polycentric regulation as a way to control large-scale cybercrime, Crime, Law and Social Change 67, 97-116',
    date: '2017 (online 2016-10-05)',
    url: 'https://doi.org/10.1007/s10611-016-9649-z',
    kind: 'peer-reviewed',
    library: true,
  },
  {
    id: 'li-2017',
    author: 'Li and Paxson',
    title: 'A Large-Scale Empirical Study of Security Patches (ACM CCS 2017, author copy)',
    date: '2017-10-30',
    url: 'https://faculty.cc.gatech.edu/~frankli/papers/li-ccs2017.pdf',
    kind: 'peer-reviewed',
  },
  {
    id: 'schneier-2018',
    author: 'Schneier',
    title: 'Artificial Intelligence and the Attack/Defense Balance (IEEE Security & Privacy, March/April 2018, essay copy)',
    date: '2018-03',
    url: 'https://www.schneier.com/essays/archives/2018/03/artificial_intellige.html',
    kind: 'primary',
  },
  {
    id: 'anderson-2019',
    author: 'Anderson, Barton, Böhme, Clayton, Gañán, Grasso, Levi, Moore and Vasek',
    title: 'Measuring the Changing Cost of Cybercrime (WEIS 2019)',
    date: '2019-06',
    url: 'https://weis2019.econinfosec.org/wp-content/uploads/sites/6/2019/05/WEIS_2019_paper_25.pdf',
    kind: 'peer-reviewed',
  },
  {
    id: 'garfinkel-2019',
    author: 'Garfinkel and Dafoe',
    title: 'How does the offense-defense balance scale? Journal of Strategic Studies 42(6), 736-763 (open access)',
    date: '2019',
    url: 'https://doi.org/10.1080/01402390.2019.1631810',
    kind: 'peer-reviewed',
  },
  {
    id: 'collier-2019',
    author: 'Collier, Thomas, Clayton and Hutchings',
    title: 'Booting the Booters: Evaluating the Effects of Police Interventions in the Market for Denial-of-Service Attacks (IMC 2019, author copy)',
    date: '2019-10-21',
    url: 'https://www.cl.cam.ac.uk/~ah793/papers/2019booting.pdf',
    kind: 'peer-reviewed',
  },
  {
    id: 'holt-2019',
    author: 'Holt, Brewer and Goldsmith',
    title: 'Digital Drift and the "Sense of Injustice": Counter-Productive Policing of Youth Cybercrime, Deviant Behavior 40(9), 1144-1156',
    date: '2019 (online 2018-05-21)',
    url: 'https://doi.org/10.1080/01639625.2018.1472927',
    kind: 'peer-reviewed',
    library: true,
  },
  {
    id: 'vandeweijer-2019',
    author: 'van de Weijer, Leukfeldt and Bernasco',
    title: 'Determinants of reporting cybercrime: A comparison between identity theft, consumer fraud, and hacking, European Journal of Criminology 16(4), 486-508',
    date: '2019 (online 2018-05-19)',
    url: 'https://doi.org/10.1177/1477370818773610',
    kind: 'peer-reviewed',
    library: true,
  },
  {
    id: 'collier-2021',
    author: 'Collier, Clayton, Hutchings and Thomas',
    title: 'Cybercrime is (often) boring: infrastructure and alienation in a deviant subculture (British Journal of Criminology 61(5), accepted manuscript)',
    date: '2021-04-15',
    url: 'https://strathprints.strath.ac.uk/76156/1/Collier_etal_BJC_2021_Cybercrime_is_often_boring_infrastructure_and_alientation.pdf',
    kind: 'peer-reviewed',
  },
  {
    id: 'lohn-2022',
    author: 'Lohn and Jackson (CSET, Georgetown)',
    title: 'Will AI Make Cyber Swords or Shields?',
    date: '2022-08',
    url: 'https://cset.georgetown.edu/publication/will-ai-make-cyber-swords-or-shields/',
    kind: 'primary',
  },
  {
    id: 'epss-2021',
    author: 'Jacobs, Romanosky, Edwards, Adjerid and Roytman',
    title: 'Exploit Prediction Scoring System (EPSS), Digital Threats: Research and Practice 2(3)',
    date: '2021-07-09',
    url: 'https://doi.org/10.1145/3436242',
    kind: 'peer-reviewed',
  },
  {
    id: 'jacobs-2023',
    author: 'Jacobs, Romanosky, Suciu, Edwards and Sarabi',
    title: 'Enhancing Vulnerability Prioritization: Data-Driven Exploit Predictions with Community-Driven Insights, arXiv:2302.14172',
    date: '2023-02-27',
    url: 'https://arxiv.org/abs/2302.14172',
    kind: 'preprint',
  },
  {
    id: 'grace-2024',
    author: 'Grace, Stewart, Sandkühler, Thomas, Weinstein-Raun, Brauner, Korzekwa',
    title: 'Thousands of AI Authors on the Future of AI (survey of 2,778 researchers), arXiv:2401.02843',
    date: '2024-01-05 (v1; v3 revised 2025-10-08)',
    url: 'https://arxiv.org/abs/2401.02843',
    kind: 'primary',
  },
  {
    id: 'kapoor-2024',
    author: 'Kapoor, Bommasani and others',
    title: 'On the Societal Impact of Open Foundation Models, arXiv:2403.07918',
    date: '2024-02-27',
    url: 'https://arxiv.org/abs/2403.07918',
    kind: 'preprint',
  },
  {
    id: 'malla-2024',
    author: 'Lin, Cui, Liao and Wang',
    title: 'Malla: Demystifying Real-world Large Language Model Integrated Malicious Services (USENIX Security 2024), arXiv:2401.03315',
    date: '2024-01-06',
    url: 'https://arxiv.org/abs/2401.03315',
    kind: 'peer-reviewed',
  },
  {
    id: 'ncsc-2024',
    author: 'UK National Cyber Security Centre',
    title: 'The near-term impact of AI on the cyber threat',
    date: '2024-01-24',
    url: 'https://www.ncsc.gov.uk/report/impact-of-ai-on-cyber-threat',
    kind: 'primary',
  },
  {
    id: 'hk-2024',
    author: 'Hong Kong Free Press, reporting a Hong Kong Police briefing',
    title: 'Multinational loses HK$200 million to deepfake video conference scam, Hong Kong police say',
    date: '2024-02-05',
    url: 'https://hongkongfp.com/2024/02/05/multinational-loses-hk200-million-to-deepfake-video-conference-scam-hong-kong-police-say/',
    kind: 'reporting',
  },
  {
    id: 'msft-2024',
    author: 'Microsoft Threat Intelligence, with OpenAI',
    title: 'Staying ahead of threat actors in the age of AI',
    date: '2024-02-14',
    url: 'https://www.microsoft.com/en-us/security/blog/2024/02/14/staying-ahead-of-threat-actors-in-the-age-of-ai/',
    kind: 'primary',
  },
  {
    id: 'fang-2024',
    author: 'Fang, Bindu, Gupta and Kang',
    title: 'LLM Agents can Autonomously Exploit One-day Vulnerabilities, arXiv:2404.08144',
    date: '2024-04-11',
    url: 'https://arxiv.org/abs/2404.08144',
    kind: 'preprint',
  },
  {
    id: 'zhu-2024',
    author: 'Zhu, Kellermann, Gupta, Li, Fang, Bindu and Kang',
    title: 'Teams of LLM Agents can Exploit Zero-Day Vulnerabilities, arXiv:2406.01637',
    date: '2024-06-02 (v2 2025-03-30)',
    url: 'https://arxiv.org/abs/2406.01637',
    kind: 'preprint',
  },
  {
    id: 'cybench-2024',
    author: 'Zhang, Perry, Dulepet and others',
    title: 'Cybench: A Framework for Evaluating Cybersecurity Capabilities and Risks of Language Models (ICLR 2025), arXiv:2408.08926',
    date: '2024-08-15',
    url: 'https://arxiv.org/abs/2408.08926',
    kind: 'peer-reviewed',
  },
  {
    id: 'cse3-2024',
    author: 'Wan, Nikolaidis, Song and others (Meta)',
    title: 'CyberSecEval 3: Advancing the Evaluation of Cybersecurity Risks and Capabilities in Large Language Models, arXiv:2408.01605',
    date: '2024-08-02 (revised 2024-09-06)',
    url: 'https://arxiv.org/abs/2408.01605',
    kind: 'preprint',
  },
  {
    id: 'gtte-2024',
    author: 'Google Threat Intelligence (Mandiant): Charrier and Weiner',
    title: 'How Low Can You Go? An Analysis of 2023 Time-to-Exploit Trends',
    date: '2024-10-15',
    url: 'https://cloud.google.com/blog/topics/threat-intelligence/time-to-exploit-trends-2023',
    kind: 'primary',
  },
  {
    id: 'tidelift-2024',
    author: 'Tidelift',
    title: 'The 2024 Tidelift Maintainer Impact Report',
    date: '2024-11',
    url: 'https://www.sonarsource.com/the-2024-tidelift-maintainer-impact-report.pdf',
    kind: 'primary',
  },
  {
    id: 'bigsleep-2024',
    author: 'Google Project Zero and Google DeepMind',
    title: 'From Naptime to Big Sleep: Using Large Language Models To Catch Vulnerabilities In Real-World Code',
    date: '2024-11-01',
    url: 'https://projectzero.google/2024/10/from-naptime-to-big-sleep.html',
    kind: 'primary',
  },
  {
    id: 'heiding-2024',
    author: 'Heiding, Lermen, Kao, Schneier and Vishwanath',
    title: 'Evaluating Large Language Models\' Capability to Launch Fully Automated Spear Phishing Campaigns, arXiv:2412.00586',
    date: '2024-11-30',
    url: 'https://arxiv.org/abs/2412.00586',
    kind: 'preprint',
  },
  {
    id: 'chainalysis-2025',
    author: 'Chainalysis',
    title: 'Ransomware payments in the 2025 Crypto Crime Report (data for 2024)',
    date: '2025-02-05',
    url: 'https://www.chainalysis.com/blog/crypto-crime-ransomware-victim-extortion-2025/',
    kind: 'primary',
  },
  {
    id: 'gtig-2025-01',
    author: 'Google Threat Intelligence Group',
    title: 'Adversarial Misuse of Generative AI',
    date: '2025-01-29',
    url: 'https://cloud.google.com/blog/topics/threat-intelligence/adversarial-misuse-generative-ai',
    kind: 'primary',
  },
  {
    id: 'metr-2025',
    author: 'METR',
    title: 'Measuring AI Ability to Complete Long Tasks',
    date: '2025-03-19',
    url: 'https://metr.org/blog/2025-03-19-measuring-ai-ability-to-complete-long-tasks/',
    kind: 'primary',
  },
  {
    id: 'cvebench-2025',
    author: 'Zhu, Kellermann, Bowman and others',
    title: 'CVE-Bench: A Benchmark for AI Agents\' Ability to Exploit Real-World Web Application Vulnerabilities, arXiv:2503.17332',
    date: '2025-03-21',
    url: 'https://arxiv.org/abs/2503.17332',
    kind: 'preprint',
  },
  {
    id: 'ai2027-2025',
    author: 'Kokotajlo, Alexander, Larsen, Lifland and Dean',
    title: 'AI 2027 (scenario)',
    date: '2025-04-03',
    url: 'https://ai-2027.com/',
    kind: 'primary',
  },
  {
    id: 'narayanan-2025',
    author: 'Narayanan and Kapoor (Knight First Amendment Institute)',
    title: 'AI as Normal Technology',
    date: '2025-04-15',
    url: 'https://knightcolumbia.org/content/ai-as-normal-technology',
    kind: 'primary',
  },
  {
    id: 'ncsc-2025',
    author: 'UK National Cyber Security Centre',
    title: 'Impact of AI on cyber threat from now to 2027',
    date: '2025-05-07',
    url: 'https://www.ncsc.gov.uk/report/impact-ai-cyber-threat-now-2027',
    kind: 'primary',
  },
  {
    id: 'cybergym-2025',
    author: 'Wang, Shi, He, Cai, Zhang and Song',
    title: 'CyberGym: Evaluating AI Agents\' Real-World Cybersecurity Capabilities at Scale (ICLR 2026), arXiv:2506.02548',
    date: '2025-06-03 (v3 2026-03-24)',
    url: 'https://arxiv.org/abs/2506.02548',
    kind: 'peer-reviewed',
  },
  {
    id: 'titotal-2025',
    author: 'titotal',
    title: 'A deep critique of AI 2027\'s bad timeline models',
    date: '2025-06-19',
    url: 'https://titotal.substack.com/p/a-deep-critique-of-ai-2027s-bad-timeline',
    kind: 'primary',
  },
  {
    id: 'xbow-2025',
    author: 'XBOW',
    title: 'The road to Top 1: How XBOW did it',
    date: '2025-06-24',
    url: 'https://xbow.com/blog/top-1-how-xbow-did-it/',
    kind: 'primary',
  },
  {
    id: 'aixcc-2025',
    author: 'DARPA',
    title: 'AI Cyber Challenge marks pivotal inflection point for cyber defense',
    date: '2025-08-08',
    url: 'https://www.darpa.mil/news/2025/aixcc-results',
    kind: 'primary',
  },
  {
    id: 'anthropic-2025-08',
    author: 'Anthropic',
    title: 'Detecting and countering misuse of AI: August 2025',
    date: '2025-08-27',
    url: 'https://www.anthropic.com/news/detecting-countering-misuse-aug-2025',
    kind: 'primary',
  },
  {
    id: 'gtig-2025-11',
    author: 'Google Threat Intelligence Group',
    title: 'GTIG AI Threat Tracker: Advances in Threat Actor Usage of AI Tools',
    date: '2025-11-05',
    url: 'https://cloud.google.com/blog/topics/threat-intelligence/threat-actor-usage-of-ai-tools',
    kind: 'primary',
  },
  {
    id: 'enisa-2025',
    author: 'ENISA',
    title: 'ETL 2025: EU consistently targeted by diverse yet convergent threat groups (Threat Landscape 2025)',
    date: '2025-10-01',
    url: 'https://www.enisa.europa.eu/news/etl-2025-eu-consistently-targeted-by-diverse-yet-convergent-threat-groups',
    kind: 'primary',
  },
  {
    id: 'anthropic-2025-11',
    author: 'Anthropic',
    title: 'Disrupting the first reported AI-orchestrated cyber espionage campaign',
    date: '2025-11-13',
    url: 'https://www.anthropic.com/news/disrupting-AI-espionage',
    kind: 'primary',
  },
  {
    id: 'aisi-2025',
    author: 'UK AI Security Institute',
    title: 'Frontier AI Trends Report',
    date: '2025-12-18',
    url: 'https://www.aisi.gov.uk/frontier-ai-trends-report',
    kind: 'primary',
  },
  {
    id: 'metr-2026-01',
    author: 'METR',
    title: 'Time Horizon 1.1',
    date: '2026-01-29',
    url: 'https://metr.org/blog/2026-1-29-time-horizon-1-1/',
    kind: 'primary',
  },
  {
    id: 'iasr-2026',
    author: 'Bengio (chair) and others',
    title: 'International AI Safety Report 2026',
    date: '2026-02-03',
    url: 'https://internationalaisafetyreport.org/publication/international-ai-safety-report-2026',
    kind: 'primary',
  },
  {
    id: 'crowdstrike-2026',
    author: 'CrowdStrike',
    title: '2026 Global Threat Report (press release)',
    date: '2026-02-24',
    url: 'https://www.crowdstrike.com/en-us/press-releases/2026-crowdstrike-global-threat-report/',
    kind: 'primary',
  },
  {
    id: 'chainalysis-2026',
    author: 'Chainalysis',
    title: 'Crypto Ransomware: 2026 Crypto Crime Report (data for 2025)',
    date: '2026-02-26',
    url: 'https://www.chainalysis.com/blog/crypto-ransomware-2026/',
    kind: 'primary',
  },
  {
    id: 'mtrends-2026',
    author: 'Google Threat Intelligence (Mandiant)',
    title: 'M-Trends 2026: Data, Insights, and Strategies From the Frontlines',
    date: '2026-03-23',
    url: 'https://cloud.google.com/blog/topics/threat-intelligence/m-trends-2026',
    kind: 'primary',
  },
  {
    id: 'ftc-2026',
    author: 'US Federal Trade Commission',
    title: 'FTC Testifies before the Joint Economic Committee on Agency’s Efforts to Combat Fraud',
    date: '2026-03-25',
    url: 'https://www.ftc.gov/news-events/news/press-releases/2026/03/ftc-testifies-joint-economic-committee-agencys-efforts-combat-fraud',
    kind: 'primary',
  },
  {
    id: 'aifutures-2026',
    author: 'Kokotajlo, Lifland and Halstead',
    title: 'Q1 2026 Timelines Update',
    date: '2026-04-02',
    url: 'https://www.lesswrong.com/posts/XLLjqMxETva3ABtsK/q1-2026-timelines-update',
    kind: 'primary',
  },
  {
    id: 'glasswing-2026-04',
    author: 'Anthropic',
    title: 'Project Glasswing: Securing critical software for the AI era',
    date: '2026-04-07',
    url: 'https://www.anthropic.com/glasswing',
    kind: 'primary',
  },
  {
    id: 'mythos-2026-04',
    author: 'Anthropic',
    title: "Claude Mythos Preview's cybersecurity capabilities",
    date: '2026-04-07',
    url: 'https://www.anthropic.com/research/mythos-preview',
    kind: 'primary',
  },
  {
    id: 'nist-nvd-2026',
    author: 'NIST',
    title: 'NIST Updates NVD Operations to Address Record CVE Growth',
    date: '2026-04-15',
    url: 'https://www.nist.gov/news-events/news/2026/04/nist-updates-nvd-operations-address-record-cve-growth',
    kind: 'primary',
  },
  {
    id: 'ic3-2025',
    author: 'FBI Internet Crime Complaint Center',
    title: '2025 Internet Crime Report',
    date: '2026-04 (PDF dated 2026-04-16)',
    url: 'https://www.ic3.gov/AnnualReport/Reports/2025_IC3Report.pdf',
    kind: 'primary',
  },
  {
    id: 'metr-2026-05',
    author: 'METR',
    title: 'Frontier Risk Report (February to March 2026)',
    date: '2026-05-19',
    url: 'https://metr.org/blog/2026-05-19-frontier-risk-report/',
    kind: 'primary',
  },
  {
    id: 'dbir-2026',
    author: 'Verizon',
    title: '2026 Data Breach Investigations Report (PDF dated 2026-05-19)',
    date: '2026-05',
    url: 'https://www.verizon.com/business/resources/reports/dbir/',
    kind: 'primary',
  },
  {
    id: 'glasswing-2026-05',
    author: 'Anthropic',
    title: 'Project Glasswing: An initial update',
    date: '2026-05-22',
    url: 'https://www.anthropic.com/research/glasswing-initial-update',
    kind: 'primary',
  },
  {
    id: 'glasswing-2026-06',
    author: 'Anthropic',
    title: 'Expanding Project Glasswing',
    date: '2026-06-02',
    url: 'https://www.anthropic.com/news/expanding-project-glasswing',
    kind: 'primary',
  },
  {
    id: 'cisa-bod-2026',
    author: 'CISA',
    title: 'CISA Issues New Directive Improving How Federal Agencies Prioritize the Mitigation of Cyber Vulnerabilities (BOD 26-04)',
    date: '2026-06-10',
    url: 'https://www.cisa.gov/news-events/news/cisa-issues-new-directive-improving-how-federal-agencies-prioritize-mitigation-cyber-vulnerabilities',
    kind: 'primary',
  },
  {
    id: 'cisa-patch-2026',
    author: 'CISA: Butera and Spring',
    title: 'Patch Smarter, Not Harder',
    date: '2026-06-10',
    url: 'https://www.cisa.gov/news-events/news/patch-smarter-not-harder',
    kind: 'primary',
  },
  {
    id: 'caisi-2026-09',
    author: 'NIST Center for AI Standards and Innovation (CAISI)',
    title: "CAISI's Assessment of Z.ai's GLM-5.3 Cyber Capabilities",
    date: '2026-09-17',
    url: 'https://www.nist.gov/news-events/news/2026/09/caisis-assessment-zais-glm-53-cyber-capabilities',
    kind: 'primary',
  },
  {
    id: 'anthropic-2026-09',
    author: 'Anthropic',
    title: 'GLM-5.3 and the spread of advanced cyber capabilities',
    date: '2026-09-29',
    url: 'https://anthropic.com/research/glm-5-3-and-the-spread-of-advanced-cyber-capabilities',
    kind: 'primary',
  },
  {
    id: 'cisa-kev-2026',
    author: 'CISA',
    title: 'Known Exploited Vulnerabilities catalog, JSON feed version 2026.10.04 (counts are mine)',
    date: '2026-10-04',
    url: 'https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json',
    kind: 'primary',
  },
] as const satisfies ReadonlyArray<PaperSource>;

export type PaperSourceId = (typeof PAPER_SOURCES)[number]['id'];

export function sourceNumber(id: PaperSourceId): number {
  return PAPER_SOURCES.findIndex((s) => s.id === id) + 1;
}

export function sourceById(id: PaperSourceId): PaperSource {
  return PAPER_SOURCES.find((s) => s.id === id) as PaperSource;
}
