export type HoldModelFrame = {
  scale: number;
  xOffset?: number;
  yOffset?: number;
  floatIntensity: number;
  rotationIntensity: number;
  floatSpeed: number;
  orbit: boolean;
  zoom: boolean;
  autoRotate: boolean;
  autoRotateSpeed: number;
  environmentIntensity: number;
};

export type HoldModelSource = {
  source: string;
  license: string;
  credit: string;
};

export type HoldModel = HoldModelSource & {
  id: string;
  label: string;
  src: `/${string}.glb`;
  frame: HoldModelFrame;
};

export const HOLD_MODELS = {
  spectre: {
    id: 'spectre',
    label: 'Spectre',
    src: '/spectre.glb',
    frame: {
      scale: 4.0,
      yOffset: -0.3,
      floatIntensity: 0.7,
      rotationIntensity: 0.8,
      floatSpeed: 1.6,
      orbit: false,
      zoom: false,
      autoRotate: true,
      autoRotateSpeed: 0.6,
      environmentIntensity: 1.2,
    },
    source: 'Existing project asset at public/spectre.glb',
    license: 'Provenance not yet recorded',
    credit: 'No external credit is currently recorded',
  },
  calibration: {
    id: 'calibration',
    label: 'Calibration',
    src: '/models/calibration.glb',
    frame: {
      scale: 2.35,
      floatIntensity: 0.7,
      rotationIntensity: 0.35,
      floatSpeed: 1.2,
      orbit: false,
      zoom: false,
      autoRotate: true,
      autoRotateSpeed: 0.45,
      environmentIntensity: 1.2,
    },
    source: 'Generated by scripts/generate-hold-calibration-glb.mjs',
    license: 'Project-owned original asset, no reuse license granted',
    credit: 'MYTHCORP calibration geometry',
  },
} as const satisfies Record<string, HoldModel>;

export type HoldModelId = keyof typeof HOLD_MODELS;
export const HOLD_MODEL_IDS = Object.keys(HOLD_MODELS) as HoldModelId[];

export const DEFAULT_HOLD_MODEL_ID = 'spectre' satisfies HoldModelId;
export const DEFAULT_HOLD_MODEL = HOLD_MODELS[DEFAULT_HOLD_MODEL_ID];

export function resolveHoldModel(modelId?: string | null): HoldModel {
  if (modelId && Object.hasOwn(HOLD_MODELS, modelId)) {
    return HOLD_MODELS[modelId as HoldModelId];
  }

  return DEFAULT_HOLD_MODEL;
}
